### ISSUE TITLE
The game doesn't work

### ISSUE THREAD

**Issue by Tran-Hong-Quan** [VladGGDev/Falling-sand-in-unity#1]
Your code is so cool, but i don't know how to make the game work, i only can draw into the Scene/Sprite Renderer

https://github.com/VladGGDev/Falling-sand-in-unity/assets/95110396/a93db468-2b48-4d82-9c2e-a443b2c7ab65

**Comment by VladGGDev** [comment]
Hello, I broke something in the last commit. I would suggest using a previous version but I don't think you can. I will try to fix it today and release a version of the working project.

**Comment by VladGGDev** [comment]
Ok, I have just released a previous version you can use that works now. A new one with changes to the chunks and simulation will come when I stop being lazy and fix the things I broke.
